---
title: A title
subtitle: A subtitle
format: clean-revealjs
author:
  - name: Your Name
    email: alias@email.com
    affiliations: Your Institution
date: last-modified
---

## Example slide

### This is a subtitle

Here we have some text that may run over several lines of the slide frame,
depending on how long it is.

- first item 
    - A sub item

Next, we'll brief review some theme-specific components.

- Note that _all_ of the standard Reveal.js
[features](https://quarto.org/docs/presentations/revealjs/)
can be used with this theme, even if we don't highlight them here.

## Additional theme classes

### Some extra things you can do with the clean theme

Special classes for emphasis

- `.alert` class for default emphasis, e.g. [important note]{.alert}.
- `.fg` class for custom colour, e.g. [important note]{.fg style="--col: #e64173"}.
- `.bg` class for custom background, e.g. [important note]{.bg style="--col: #e64173"}.

Cross-references

- `.button` class provides a Beamer-like button, e.g.
[[Summary]{.button}](#see-our-longer-demo-slides)

## Want more?

### See our longer demo slides

We've deliberarely kept this template lean, to get you up and running as fast as
possible.

We provide a separate
[demo template](https://github.com/grantmcdermott/quarto-revealjs-clean-demo),
with more examples for integrating code, tables, figures, etc.

  - See the live demo slides
  [here](https://grantmcdermott.com/quarto-revealjs-clean-demo/template.html).

## Summary {#sec-summary}

### A minimalist and elegant presentation theme

The Quarto reveal.js clean theme aims to be a minimalist and elegant presention
theme. Here are some options to get you started:

Add the theme to an existing project.

```{.bash}
quarto install extension grantmcdermott/quarto-revealjs-clean
```

... or, create a new project using this slide deck as a lean template.

```{.bash}
quarto use template grantmcdermott/quarto-revealjs-clean
```

... or, create a new project using the demo slide deck as a full template.

```{.bash}
quarto use template grantmcdermott/quarto-revealjs-clean-demo
```

## Callout Notes

::: {.callout-note}
Note that there are five types of callouts, including:
`note`, `warning`, `important`, `tip`, and `caution`.
:::

::: {.callout-tip}
## Tip with Title

This is an example of a callout with a title.
:::

::: {.callout-caution collapse="true"}
## Expand To Learn About Collapse

This is an example of a 'folded' caution callout that can be expanded by the user. You can use `collapse="true"` to collapse it by default or `collapse="false"` to make a collapsible callout that is expanded by default.
:::

# Some title {background-image="images/bg/bg-background-mayan.png"}

# [Some other title]{style="color: #000000;"} {background-image="images/bg/bg-background-green-bottom.jpg"}

## Bottom slide {background-image="images/bg/bg-background-green-bottom.jpg"}

## Side content slide {background-image="images/bg/bg-background-green-side.jpg"}

# {background-image="images/bg/bg-background-green-end.jpg"}